<?php
use AranduGo\Support;
$system=is_file(__DIR__.'/../config/system.php')?require __DIR__.'/../config/system.php':[];
$socialLabels=$socialLabels??['facebook'=>'Facebook','instagram'=>'Instagram','x'=>'X','linkedin'=>'LinkedIn','youtube'=>'YouTube','tiktok'=>'TikTok','urlgo'=>'URLGO.me','whatsapp'=>'WhatsApp'];require __DIR__.'/social-icons.php';
$socialStyle=$d['socialSettings']['style']??[];$shape=in_array($socialStyle['shape']??'circle',['circle','rounded','square'],true)?$socialStyle['shape']:'circle';$customColors=($socialStyle['colorMode']??'brand')==='custom';$socialInline=$customColors?'--social-bg:'.Support::e($socialStyle['background']??'#1769d2').';--social-icon:'.Support::e($socialStyle['icon']??'#ffffff').';':'';
$footerSocials='';if(!empty($d['footer']['showSocials'])){$socialOrder=$d['socialSettings']['order']??array_keys($socialLabels);foreach($socialOrder as $network){$url=$d['socials'][$network]??'';$visible=$d['socialSettings']['visible'][$network]??true;if($url&&$visible)$footerSocials.='<a class="social-icon social-'.Support::e($network).' social-shape-'.$shape.($customColors?' social-custom-colors':'').'" style="'.$socialInline.'" href="'.Support::e($url).'" target="_blank" rel="noopener" aria-label="'.Support::e($socialLabels[$network]??$network).'">'.$socialIconMarkup($network).'<span>'.Support::e($socialLabels[$network]??$network).'</span></a>';}}
$visible=$d['contactVisibility']??[];$show=fn(string $key,string $place,bool $fallback=true):bool=>array_key_exists($place,$visible[$key]??[])?!empty($visible[$key][$place]):$fallback;
$legacyContactEnabled=!array_key_exists('showContact',$d['footer']??[])||!empty($d['footer']['showContact']);
$footerVisibility=$d['footer']['visibility']??[];$footerShows=fn(string $key):bool=>!array_key_exists($key,$footerVisibility)||!empty($footerVisibility[$key]);$items=[];
if($footerShows('logo')&&!empty($d['footer']['showLogo']))$items['logo']='<div class="footer-identity">'.((($d['header']['identityType']??'initial')==='logo'&&!empty($d['header']['logo']))?'<img src="'.Support::e($d['header']['logo']).'" alt="">':'<span class="identity-mark">'.Support::e($d['header']['initial']??'A').'</span>').'</div>';
if($footerShows('name')&&!empty($d['footer']['showName'])&&$show('name','footer',true))$items['name']='<strong class="footer-name">'.Support::e($d['header']['nameText']??$d['business']['name']).'</strong>';
if($footerShows('email')&&$show('email','footer',$legacyContactEnabled)&&!empty($d['business']['email']))$items['email']='<a class="footer-contact" href="mailto:'.Support::e($d['business']['email']).'">'.Support::e($d['business']['email']).'</a>';
if($footerShows('address')&&$show('address','footer',$legacyContactEnabled)&&!empty($d['business']['address']))$items['address']='<span class="footer-contact">⌖ '.Support::e($d['business']['address']).'</span>';
if($footerShows('hours')&&$show('hours','footer',$legacyContactEnabled)&&!empty($d['business']['hours']))$items['hours']='<span class="footer-contact">◷ '.Support::e($d['business']['hours']).'</span>';
$footerPhones='';if($footerShows('phones'))foreach($d['phones']??[] as $phone){$phoneVisible=array_key_exists('showInFooter',$phone)?!empty($phone['showInFooter']):$legacyContactEnabled;if($phoneVisible&&!empty($phone['number'])){$number=preg_replace('/\D+/','',(string)$phone['number']);$href=($phone['type']??'')==='whatsapp'?'https://wa.me/'.$number:'tel:+'.$number;$footerPhones.='<a class="footer-contact" href="'.Support::e($href).'">'.Support::e(($phone['label']??'Teléfono').': '.$phone['number']).'</a>';}}if($footerPhones!=='')$items['phones']='<div class="footer-phones">'.$footerPhones.'</div>';
if($footerShows('socials')&&$footerSocials!=='')$items['socials']='<div class="footer-links footer-socials">'.$footerSocials.'</div>';
if($footerShows('legal')&&!empty($d['footer']['showLegalLinks']))$items['legal']='<div class="footer-links footer-legal"><a href="'.Support::url('terminos.php').'">Términos de Servicio</a><a href="'.Support::url('privacidad.php').'">Políticas de Privacidad</a></div>';
if($footerShows('copyright')&&!empty($d['footer']['legalText']))$items['copyright']='<p class="footer-copy">'.Support::e($d['footer']['legalText']).'</p>';
$defaultOrder=['logo','name','email','address','hours','phones','socials','legal','copyright'];$legacy=['identity'=>['logo','name'],'contact'=>['email']];$order=[];foreach($d['footer']['order']??[] as $key){foreach($legacy[$key]??[$key] as $expanded)if(in_array($expanded,$defaultOrder,true)&&!in_array($expanded,$order,true))$order[]=$expanded;}foreach($defaultOrder as $key)if(!in_array($key,$order,true))$order[]=$key;
$fontMap=['system'=>'system-ui,-apple-system,"Segoe UI",sans-serif','modern'=>'Inter,Arial,sans-serif','classic'=>'Georgia,"Times New Roman",serif','rounded'=>'"Trebuchet MS",Verdana,sans-serif'];$fontKey=$d['typography']['font']??'system';
?><style>:root{--site-font:<?=$fontMap[$fontKey]??$fontMap['system']?>;--body-size:<?=max(14,min(20,(int)($d['typography']['bodySize']??16)))?>px;--heading-scale:<?=max(.9,min(1.12,(float)($d['typography']['headingScale']??1)))?>}.social-section .social-row .social-icon,.site-footer .footer-socials .social-icon{border-radius:<?=$shape==='square'?'0':($shape==='rounded'?'9px':'50%')?>!important}<?php if($customColors):?>.social-section .social-row .social-icon,.site-footer .footer-socials .social-icon{background:<?=Support::e($socialStyle['background']??'#1769d2')?>!important;color:<?=Support::e($socialStyle['icon']??'#ffffff')?>!important;border-color:transparent!important}<?php endif;?></style>
<footer class="site-footer" style="background:<?=Support::e($d['footer']['background']??'#fff')?>;color:<?=Support::e($d['footer']['text']??'#526078')?>"><div class="footer-main"><?php foreach($order as $key)if(isset($items[$key]))echo $items[$key];?></div><?php if(!empty($system['branding']['show_powered_by'])):?><p class="footer-powered"><strong><?=Support::e($system['branding']['powered_by_text']??'Powered by Arandu Cloud')?></strong></p><?php endif;?></footer><a class="back-to-top" href="#inicio" aria-label="Volver arriba" title="Volver arriba">↑</a><script src="<?=Support::url('assets/contact-form.js')?>?v=<?=Support::e((string)($assetVersion??'1.0.23'))?>" defer></script><script src="<?=Support::url('assets/public-ui.js')?>?v=<?=Support::e((string)($assetVersion??'1.0.23'))?>" defer></script>
