<?php
require dirname(__DIR__).'/bootstrap.php';
use AranduGo\Auth;use AranduGo\Csrf;use AranduGo\Support;
Auth::requireAdmin();Csrf::verify();
function fail(string $message,int $code=422):never{Support::json(['ok'=>false,'error'=>$message],$code);}
function csvRows(string $csv):array{$rows=[];$handle=fopen('php://temp','r+');fwrite($handle,$csv);rewind($handle);$head=fgetcsv($handle);if(!$head)return[];$head=array_map(fn($v)=>strtolower(trim(preg_replace('/^\xEF\xBB\xBF/','',$v))),$head);while(($row=fgetcsv($handle))!==false){$item=[];foreach($head as $i=>$key)$item[$key]=trim((string)($row[$i]??''));if(array_filter($item,fn($v)=>$v!==''))$rows[]=$item;}return $rows;}
function xlsxRows(string $file):array{
 if(!class_exists(ZipArchive::class)||!function_exists('simplexml_load_string'))fail('El servidor necesita las extensiones ZIP y SimpleXML para leer .xlsx.');$zip=new ZipArchive();if($zip->open($file)!==true)fail('El archivo Excel no es válido.');
 $parse=static function(string $xml){$previous=libxml_use_internal_errors(true);try{return simplexml_load_string($xml,'SimpleXMLElement',LIBXML_NONET|LIBXML_NOCDATA)?:null;}finally{libxml_clear_errors();libxml_use_internal_errors($previous);}};
 $shared=[];$xml=$zip->getFromName('xl/sharedStrings.xml');if($xml!==false){$sx=$parse($xml);if($sx)foreach($sx->si as $si){$text=(string)$si->t;if($text==='')foreach($si->r as $run)$text.=(string)$run->t;$shared[]=$text;}}
 $sheetName='xl/worksheets/sheet1.xml';$workbook=$zip->getFromName('xl/workbook.xml');$rels=$zip->getFromName('xl/_rels/workbook.xml.rels');if($workbook!==false&&$rels!==false){$wb=$parse($workbook);$rs=$parse($rels);if($wb&&$rs){$wb->registerXPathNamespace('r','http://schemas.openxmlformats.org/officeDocument/2006/relationships');$first=$wb->sheets->sheet[0]??null;$rid=$first?(string)$first->attributes('r',true)['id']:'';foreach($rs->Relationship as $rel)if((string)$rel['Id']===$rid){$target=ltrim((string)$rel['Target'],'/');$sheetName=str_starts_with($target,'xl/')?$target:'xl/'.$target;break;}}}
 $sheet=$zip->getFromName($sheetName);$zip->close();if($sheet===false)fail('El Excel debe tener datos en la primera hoja.');$sx=$parse($sheet);if(!$sx)return[];$out=[];
 foreach($sx->sheetData->row as $row){$line=[];$max=-1;foreach($row->c as $cell){$ref=(string)$cell['r'];preg_match('/([A-Z]+)/i',$ref,$m);$col=0;foreach(str_split(strtoupper($m[1]??'A')) as $ch)$col=$col*26+(ord($ch)-64);$index=max(0,$col-1);$type=(string)$cell['t'];$value=$type==='inlineStr'?(string)$cell->is->t:(string)$cell->v;if($type==='s')$value=$shared[(int)$value]??'';$line[$index]=$value;$max=max($max,$index);}if($max>=0){for($i=0;$i<=$max;$i++)$line[$i]=$line[$i]??'';ksort($line);$out[]=$line;}}
 if(!$out)return[];$head=array_map(fn($v)=>strtolower(trim(preg_replace('/^\xEF\xBB\xBF/','',(string)$v))),array_shift($out));return array_values(array_filter(array_map(function($row)use($head){$item=[];foreach($head as $i=>$key)if($key!=='')$item[$key]=trim((string)($row[$i]??''));return $item;},$out),fn($row)=>array_filter($row,fn($v)=>$v!=='')));
}
if(empty($_FILES['content'])||$_FILES['content']['error']!==UPLOAD_ERR_OK)fail('No se recibió el archivo.');$file=$_FILES['content'];if($file['size']>10*1024*1024)fail('El archivo supera los 10 MB.');$ext=strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION));try{if($ext==='json'){$data=json_decode((string)file_get_contents($file['tmp_name']),true);if(!is_array($data)||empty($data['business'])||!is_array($data['modules']??null))fail('El JSON no contiene una configuración válida.');Support::json(['ok'=>true,'mode'=>'full','data'=>$data]);}$rows=$ext==='csv'?csvRows((string)file_get_contents($file['tmp_name'])):($ext==='xlsx'?xlsxRows($file['tmp_name']):fail('Usá JSON, CSV o Excel .xlsx.'));Support::json(['ok'=>true,'mode'=>'rows','rows'=>$rows]);}catch(Throwable $e){fail($e->getMessage(),500);}
