<?php
declare(strict_types=1);

$root=dirname(__DIR__); $lock=$root.'/storage/installed.lock'; $errors=[]; $done=false;
if (is_file($lock)) { http_response_code(403); exit('El instalador está bloqueado.'); }

foreach (['storage','storage/backups','storage/logs','storage/updates','uploads'] as $directory) {
 $path=$root.'/'.$directory;
 if(!is_dir($path) && !mkdir($path,0755,true) && !is_dir($path))$errors[]='No se pudo crear la carpeta '.$directory.'.';
}

function h(string $v): string { return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
function cpanelCall(string $url,string $user,string $token,string $module,string $function,array $params): array {
 $endpoint=rtrim($url,'/').'/execute/'.$module.'/'.$function.'?'.http_build_query($params);
 $ch=curl_init($endpoint); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: cpanel '.$user.':'.$token],CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_TIMEOUT=>25]);
 $raw=curl_exec($ch); if($raw===false)throw new RuntimeException('No se pudo conectar con la API de cPanel: '.curl_error($ch)); $status=curl_getinfo($ch,CURLINFO_RESPONSE_CODE); curl_close($ch);
 $data=json_decode($raw,true); if($status>=400||empty($data['status']))throw new RuntimeException($data['errors'][0]??'cPanel rechazó la operación.'); return $data;
}
function phpConfig(array $cfg): string { return "<?php\nreturn ".var_export($cfg,true).";\n"; }

$checks=[
 'PHP 8.1 o superior'=>version_compare(PHP_VERSION,'8.1.0','>='), 'PDO MySQL'=>extension_loaded('pdo_mysql'), 'JSON'=>extension_loaded('json'), 'mbstring'=>extension_loaded('mbstring'), 'OpenSSL'=>extension_loaded('openssl'), 'ZIP'=>extension_loaded('zip'), 'cURL (API cPanel)'=>extension_loaded('curl'), 'config escribible'=>is_writable($root.'/config'), 'storage escribible'=>is_writable($root.'/storage'), 'uploads escribible'=>is_writable($root.'/uploads')
];

if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  foreach(['PHP 8.1 o superior','PDO MySQL','JSON','mbstring','OpenSSL','ZIP','config escribible','storage escribible','uploads escribible'] as $required)if(empty($checks[$required]))throw new RuntimeException('No se cumple: '.$required);
  $mode=$_POST['db_mode']??'existing'; $prefix=preg_replace('/[^a-zA-Z0-9_]/','',$_POST['db_prefix']??'ago_'); if($prefix==='')$prefix='ago_';
  $dbHost=trim($_POST['db_host']??'localhost'); $dbName=trim($_POST['db_name']??''); $dbUser=trim($_POST['db_user']??''); $dbPass=(string)($_POST['db_password']??'');
  if($mode==='cpanel'){
   if(!extension_loaded('curl'))throw new RuntimeException('cURL es necesario para creación automática.');
   $cpUrl=trim($_POST['cpanel_url']??''); $cpUser=trim($_POST['cpanel_user']??''); $cpToken=(string)($_POST['cpanel_token']??''); $dbSuffix=preg_replace('/[^a-zA-Z0-9_]/','',$_POST['db_suffix']??'arandugo'); $userSuffix=preg_replace('/[^a-zA-Z0-9_]/','',$_POST['db_user_suffix']??'arandugo');
   cpanelCall($cpUrl,$cpUser,$cpToken,'Mysql','create_database',['name'=>$dbSuffix]); cpanelCall($cpUrl,$cpUser,$cpToken,'Mysql','create_user',['name'=>$userSuffix,'password'=>$dbPass]); cpanelCall($cpUrl,$cpUser,$cpToken,'Mysql','set_privileges_on_database',['user'=>$userSuffix,'database'=>$dbSuffix,'privileges'=>'ALL PRIVILEGES']);
   $dbName=$cpUser.'_'.$dbSuffix; $dbUser=$cpUser.'_'.$userSuffix;
  }
  if($dbName===''||$dbUser===''||$dbPass==='')throw new RuntimeException('Completá los datos de la base de datos.');
  $pdo=new PDO("mysql:host={$dbHost};port=3306;dbname={$dbName};charset=utf8mb4",$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);
  $occupied=$pdo->query("SHOW TABLES LIKE ".$pdo->quote($prefix.'%'))->fetchColumn();if($occupied!==false)throw new RuntimeException('El prefijo ya está ocupado. Elegí un prefijo exclusivo para esta instalación.');
  $schema=str_replace('{{prefix}}',$prefix,file_get_contents($root.'/database/schema.sql')); $pdo->exec($schema);
  $site=require $root.'/database/'.(!empty($_POST['demo_content'])?'demo-accountant.php':'default-site.php');
  if(empty($_POST['demo_content'])){ $site['business']=['name'=>trim($_POST['business_name']??'Mi negocio'),'category'=>'','slogan'=>'','description'=>'','email'=>'','address'=>'','hours'=>'','mapsUrl'=>'','mapsEmbedUrl'=>''];$site['header']['nameText']=$site['business']['name'];$site['header']['logo']='';$site['hero']=array_replace($site['hero'],['title'=>'','text'=>'','image'=>'']);$site['about']=array_replace($site['about'],['title'=>'','text'=>'','showInMenu'=>false]);$site['phones']=[];$site['services']=[];$site['gallery']=[];$site['gallerySettings']=['title'=>'','introHtml'=>''];$site['socials']=array_fill_keys(array_keys($site['socials']??[]),'');foreach($site['freeSections']??[] as $i=>$section)$site['freeSections'][$i]=array_replace($section,['title'=>'','menuLabel'=>'','publicLabel'=>'','showInMenu'=>false,'html'=>'','media'=>[],'ctaLabel'=>'','ctaUrl'=>'']);foreach($site['modules']??[] as $i=>$module)if(!in_array($module['key']??'',['hero','contact'],true))$site['modules'][$i]['active']=false;$site['demo']=['active'=>false,'progress'=>[]]; }
  $json=json_encode($site,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); $stmt=$pdo->prepare("INSERT INTO `{$prefix}site_profiles` (id,draft_json,published_json,published_at) VALUES (1,?,?,NOW()) ON DUPLICATE KEY UPDATE draft_json=VALUES(draft_json),published_json=VALUES(published_json)"); $stmt->execute([$json,$json]);
  $name=trim($_POST['admin_name']??'Administrador'); $username=trim($_POST['admin_user']??'admin'); $email=filter_var($_POST['admin_email']??'',FILTER_VALIDATE_EMAIL); $password=(string)($_POST['admin_password']??'');
  if(!$email||strlen($password)<10)throw new RuntimeException('El administrador necesita un correo válido y una contraseña de al menos 10 caracteres.');
  $stmt=$pdo->prepare("INSERT INTO `{$prefix}users` (name,username,email,password_hash,role) VALUES (?,?,?,?, 'admin')"); $stmt->execute([$name,$username,$email,password_hash($password,PASSWORD_DEFAULT)]);
  $baseUrl=rtrim(trim($_POST['app_url']??''),'/'); if(!filter_var($baseUrl,FILTER_VALIDATE_URL))throw new RuntimeException('La URL del sitio no es válida.');
  $config=['app'=>['name'=>'Arandu Go','url'=>$baseUrl,'timezone'=>$_POST['timezone']??'America/Asuncion','debug'=>false,'key'=>bin2hex(random_bytes(32)),'version'=>'2.2.1'],'database'=>['host'=>$dbHost,'port'=>3306,'name'=>$dbName,'user'=>$dbUser,'password'=>$dbPass,'charset'=>'utf8mb4','prefix'=>$prefix],'mail'=>['transport'=>$_POST['mail_transport']??'mail','from_email'=>trim($_POST['from_email']??$email),'from_name'=>trim($_POST['from_name']??'Arandu Go'),'sendmail_path'=>trim($_POST['sendmail_path']??'/usr/sbin/sendmail -bs'),'smtp'=>['host'=>trim($_POST['smtp_host']??''),'port'=>(int)($_POST['smtp_port']??587),'security'=>$_POST['smtp_security']??'tls','username'=>trim($_POST['smtp_user']??''),'password'=>(string)($_POST['smtp_password']??'')]],'recaptcha'=>['secret_key'=>(string)($_POST['recaptcha_secret']??'')]];
  if(file_put_contents($root.'/config/config.php',phpConfig($config),LOCK_EX)===false)throw new RuntimeException('No se pudo crear config/config.php.'); chmod($root.'/config/config.php',0600);
  file_put_contents($lock,date(DATE_ATOM)."\n",LOCK_EX); $done=true;
 }catch(Throwable $e){$errors[]=$e->getMessage();}
}
$https=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')||($_SERVER['HTTP_X_FORWARDED_PROTO']??'')==='https';$scriptDir=str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'/install/index.php'));$basePath=preg_replace('#/install$#','',$scriptDir);$suggestedUrl=($https?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').($basePath==='/'?'':$basePath);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Instalar Arandu Go PHP 2.2.1</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f6fb;color:#17233b;font:15px system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:980px;margin:35px auto;padding:0 20px}.brand{display:flex;align-items:center;gap:12px;margin-bottom:22px}.logo{display:grid;place-items:center;width:44px;height:44px;border-radius:12px;background:#1769d2;color:white;font-weight:900}.card{background:white;border:1px solid #dce5f0;border-radius:18px;padding:26px;margin:16px 0;box-shadow:0 10px 35px #17365d0c}h1{margin:0;font-size:28px}h2{font-size:18px;margin:0 0 16px;color:#1769d2}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{display:grid;gap:6px;font-weight:700;font-size:13px}input,select{padding:11px;border:1px solid #ccd7e6;border-radius:9px;background:#fbfcfe}.full{grid-column:1/-1}.check{display:flex;gap:9px;align-items:center}.check input{width:auto}.checks{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.checks span{padding:8px;border-radius:8px;background:#eef3f8}.checks .ok{color:#08733f;background:#eaf8f0}.checks .bad{color:#a12b2b;background:#fff0f0}.advanced{display:none}.errors{background:#fff0f0;color:#922;padding:14px;border-radius:10px}.success{text-align:center;padding:40px}.success a,button{display:inline-block;border:0;border-radius:10px;background:#0d1c36;color:white;padding:12px 18px;font-weight:800;text-decoration:none;cursor:pointer}@media(max-width:700px){.grid,.checks{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><div class="brand"><div class="logo">A</div><div><h1>Arandu Go PHP</h1><span>Asistente de instalación para cPanel · versión 2.2.1</span></div></div>
<?php if($done):?><section class="card success"><h2>Instalación completada</h2><p>La base de datos, el administrador y la configuración fueron creados. El instalador quedó bloqueado.</p><a href="<?=h(rtrim($_POST['app_url'],'/').'/dashboardcliente/')?>">Abrir panel de control</a></section>
<?php else:?><?php if($errors):?><div class="errors"><?=implode('<br>',array_map('h',$errors))?></div><?php endif;?><form method="post">
<section class="card"><h2>1. Verificación del servidor</h2><div class="checks"><?php foreach($checks as $label=>$ok):?><span class="<?=$ok?'ok':'bad'?>"><?=$ok?'✓':'×'?> <?=h($label)?></span><?php endforeach;?></div></section>
<section class="card"><h2>2. Sitio y base de datos</h2><div class="grid"><label class="full">URL pública<input name="app_url" value="<?=h($_POST['app_url']??$suggestedUrl)?>" required></label><label>Nombre inicial del comercio<input name="business_name" value="<?=h($_POST['business_name']??'Mi comercio')?>"></label><label>Zona horaria<select name="timezone"><option>America/Asuncion</option><option>America/Argentina/Buenos_Aires</option><option>America/Montevideo</option><option>America/Sao_Paulo</option><option>UTC</option></select></label><fieldset class="full"><legend>Contenido inicial</legend><label class="check"><input type="radio" name="demo_content" value="1" checked> Instalar con contenido de ejemplo: Estudio Contable Horizonte</label><label class="check"><input type="radio" name="demo_content" value="0"> Comenzar con el sitio vacío</label></fieldset><label>Modo de base<select name="db_mode" id="dbMode"><option value="existing">Base creada en cPanel</option><option value="cpanel">Creación automática por API de cPanel</option></select></label><label>Host MySQL<input name="db_host" value="localhost" required></label><label>Nombre completo de base<input name="db_name" placeholder="usuario_arandugo"></label><label>Usuario completo de base<input name="db_user" placeholder="usuario_arandugo"></label><label>Contraseña MySQL<input type="password" name="db_password" required></label><label>Prefijo de tablas<input name="db_prefix" value="ago_" required></label></div><div id="cpanelFields" class="advanced grid"><label>URL de cPanel<input name="cpanel_url" placeholder="https://servidor:2083"></label><label>Usuario cPanel<input name="cpanel_user"></label><label class="full">Token API cPanel<input type="password" name="cpanel_token"></label><label>Sufijo de base<input name="db_suffix" value="arandugo"></label><label>Sufijo de usuario<input name="db_user_suffix" value="arandugo"></label></div></section>
<section class="card"><h2>3. Usuario administrador</h2><div class="grid"><label>Nombre<input name="admin_name" required></label><label>Usuario<input name="admin_user" value="admin" required></label><label>Correo<input type="email" name="admin_email" required></label><label>Contraseña (mínimo 10 caracteres)<input type="password" name="admin_password" minlength="10" required></label></div></section>
<section class="card"><h2>4. Servicio de correo y captcha</h2><div class="grid"><label>Método<select name="mail_transport" id="mailTransport"><option value="mail">PHP mail()</option><option value="sendmail">Sendmail local</option><option value="smtp">SMTP propio</option></select></label><label>Correo remitente<input type="email" name="from_email" required></label><label>Nombre remitente<input name="from_name" value="Arandu Go"></label><label>Ruta Sendmail<input name="sendmail_path" value="/usr/sbin/sendmail -bs"></label><label class="full">Clave secreta de Google reCAPTCHA v2 (opcional)<input type="password" name="recaptcha_secret"><small>La clave pública se carga después desde el dashboard; esta clave queda protegida en el servidor.</small></label></div><div id="smtpFields" class="advanced grid"><label>Host SMTP<input name="smtp_host"></label><label>Puerto<input type="number" name="smtp_port" value="587"></label><label>Seguridad<select name="smtp_security"><option value="tls">TLS / STARTTLS</option><option value="ssl">SSL</option></select></label><label>Usuario SMTP<input name="smtp_user"></label><label class="full">Contraseña SMTP<input type="password" name="smtp_password"></label></div></section><button>Instalar Arandu Go</button></form><?php endif;?></main><script>
const db=document.querySelector('#dbMode'),cp=document.querySelector('#cpanelFields'),mail=document.querySelector('#mailTransport'),smtp=document.querySelector('#smtpFields');function toggle(){cp.style.display=db.value==='cpanel'?'grid':'none';smtp.style.display=mail.value==='smtp'?'grid':'none'}db?.addEventListener('change',toggle);mail?.addEventListener('change',toggle);toggle();
</script></body></html>
