<?php
declare(strict_types=1);
$packageRoot=dirname(__DIR__);$target='';
foreach([dirname($packageRoot,2),dirname($packageRoot),$packageRoot] as $candidate){if(is_file($candidate.'/config/config.php')&&is_file($candidate.'/storage/installed.lock')){$target=$candidate;break;}}
if($target===''){header('Location: ../install/');exit;}
require $target.'/vendor/autoload.php';require_once $packageRoot.'/src/UpdateManager.php';
use AranduGo\Auth;use AranduGo\Support;use AranduGo\UpdateManager;
Auth::start();$error='';$result=null;$config=Support::config();
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!Auth::check()&&!Auth::attempt(trim($_POST['login']??''),(string)($_POST['password']??'')))throw new RuntimeException('Usuario o contraseña incorrectos.');
  if(!Auth::isAdmin())throw new RuntimeException('La actualización requiere un usuario administrador.');
  if(($_POST['confirm']??'')!=='update')throw new RuntimeException('Confirmá la actualización.');
  $result=(new UpdateManager($target,$config))->applyDirectory($packageRoot);
 }catch(Throwable $e){$error=$e->getMessage();}
}
$installed=UpdateManager::installedVersion($target,$config);$manifest=json_decode((string)file_get_contents($packageRoot.'/manifest.json'),true)?:[];
function hu(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Actualizar Arandu Go</title><style>*{box-sizing:border-box}body{margin:0;background:#f2f6fb;color:#17233b;font:16px system-ui,sans-serif}.wrap{max-width:760px;margin:40px auto;padding:20px}.card{background:#fff;border:1px solid #dce5f0;border-radius:18px;padding:28px;box-shadow:0 15px 45px #17365d12}.brand{display:flex;gap:12px;align-items:center}.mark{display:grid;place-items:center;width:42px;height:42px;border-radius:11px;background:#1769d2;color:#fff;font-weight:900}.versions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:22px 0}.versions div{padding:16px;background:#eef4fc;border-radius:11px}.versions strong{display:block;font-size:1.35rem}label{display:grid;gap:6px;margin:12px 0;font-weight:700}input{padding:12px;border:1px solid #cbd7e7;border-radius:9px}.check{display:flex;align-items:center;gap:9px}.check input{width:auto}.btn{border:0;border-radius:9px;padding:12px 17px;background:#0d1c36;color:#fff;font-weight:800;cursor:pointer}.error{background:#fff0f0;color:#922;padding:12px;border-radius:9px}.success{background:#eaf8f0;color:#075d35;padding:16px;border-radius:10px}.path{font:13px monospace;background:#f5f7fa;padding:10px;border-radius:8px;overflow-wrap:anywhere}@media(max-width:600px){.versions{grid-template-columns:1fr}}</style></head><body><main class="wrap"><section class="card"><div class="brand"><span class="mark">A</span><div><strong>Arandu Go</strong><div>Actualización segura</div></div></div><?php if($result):?><h1>Actualización completada</h1><p class="success">La versión <?=hu($result['to'])?> quedó instalada. Los datos, imágenes y claves existentes fueron conservados.</p><p>Respaldo: <strong><?=hu(basename($result['backup']))?></strong></p><a class="btn" href="<?=hu(rtrim($config['app']['url'],'/').'/dashboardcliente/')?>">Abrir dashboard</a><?php else:?><h1>Actualizar instalación</h1><div class="versions"><div>Versión instalada<strong><?=hu($installed)?></strong></div><div>Versión del paquete<strong><?=hu((string)($manifest['version']??'desconocida'))?></strong></div></div><p>Instalación detectada:</p><p class="path"><?=hu($target)?></p><?php if($error):?><p class="error"><?=hu($error)?></p><?php endif;?><form method="post"><?php if(!Auth::check()):?><label>Usuario o correo administrador<input name="login" required autocomplete="username"></label><label>Contraseña<input type="password" name="password" required autocomplete="current-password"></label><?php endif;?><label class="check"><input type="checkbox" name="confirm" value="update" required> Crear respaldo y actualizar esta instalación</label><button class="btn">Actualizar a <?=hu((string)($manifest['version']??''))?></button></form><?php endif;?></section></main></body></html>
